backend/voxel_handler/lib/voxel_handler_web/router.ex
defmodule VoxelHandlerWeb.Router do

  use VoxelHandlerWeb, :router
  # for user
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VoxelHandlerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
    error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_allow_cross do
    plug CORSPlug, origin: [~r/.*/]
    plug :accepts, ["json"]
  end

  scope "/", VoxelHandlerWeb do
    pipe_through :browser

    live "/", IndexLive, :index

    # user sign in
    get "/user/sign-in", SessionController, :new
    post "/user/sign-in", SessionController, :create
    get "/user/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/voxel_handler/api/v1", VoxelHandlerWeb do
    pipe_through :api_allow_cross
    get "/place_order", OrderController, :get_msg
    post "/place_order", OrderController, :place_order

    get "/verify_sig", SigVerifierController, :get_msg
    post "/verify_sig", SigVerifierController, :verify_sig
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard", metrics: VoxelHandlerWeb.Telemetry
  #   end
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

backend/voxel_handler/lib/voxel_handler_web/views/layout_view.ex
defmodule VoxelHandlerWeb.LayoutView do
  use VoxelHandlerWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

backend/voxel_handler/lib/voxel_handler_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

backend/voxel_handler/lib/voxel_handler_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

backend/voxel_handler/lib/voxel_handler_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "VoxelHandler", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <%= if Plug.Conn.get_session(@conn, :current_user_id) do %>
              <%= @conn
                  |> Plug.Conn.get_session(:current_user_id)
                  |> VoxelHandler.Users.User.get_by_id()
                  |> Map.get(:email)
              %>
              <%= link "Log Out", to: Routes.session_path(@conn, :delete) %>
            <% else %>
              <%= link "Sign In", to: Routes.session_path(@conn, :new) %>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>